"""adding 'shows' column to venues table.

Revision ID: 065c961c8a38
Revises: 4c4a92339e53
Create Date: 2023-06-28 10:36:39.672355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065c961c8a38'
down_revision = '4c4a92339e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shows', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_column('shows')

    # ### end Alembic commands ###
