"""added missing fields to Artist and Venue class

Revision ID: 3f858d01cd07
Revises: 7f2d4be2defc
Create Date: 2023-06-20 15:10:14.408955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f858d01cd07'
down_revision = '7f2d4be2defc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('venue_box', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('seeking_desc', sa.String(length=1000), nullable=True))

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('talent_box', sa.Boolean(), nullable=True))
        batch_op.drop_column('talent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('talent_box')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('seeking_desc')
        batch_op.drop_column('venue_box')
        batch_op.drop_column('website_link')

    # ### end Alembic commands ###
