"""created 'id' column in 'shows' table


Revision ID: 58eed7a163d0
Revises: 065c961c8a38
Create Date: 2023-06-28 12:49:46.561575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58eed7a163d0'
down_revision = '065c961c8a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.alter_column('website_link',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('seeking_desc',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=200),
               nullable=True)

    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('venue_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('artist_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_foreign_key(None, 'venues', ['venue_id'], ['id'])
        batch_op.create_foreign_key(None, 'artists', ['artist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('artist_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('venue_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('id')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.alter_column('seeking_desc',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('website_link',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
