"""synced @app.route for '/artist', '/venue', and '/show' to database

Revision ID: cd4a02e19cb0
Revises: 5df637227611
Create Date: 2023-06-22 11:35:20.732754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4a02e19cb0'
down_revision = '5df637227611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.alter_column('facebook_link',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=500),
               nullable=False)
        batch_op.alter_column('image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('website_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('seeking_desc',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.alter_column('seeking_desc',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
        batch_op.alter_column('website_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('facebook_link',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
